export const ROUTES = {
    DASHBOARD: "/",
    PRODUCTS: "/products",
    TOPPINGS: "/toppings",
    PRODUCT_NEW: "/products/new",
    productEdit: (id: string) => `/products/${id}/edit`,
    CATEGORIES: "/categories",
    ORDERS: "/orders",
    ORDER_NEW: "/orders/new",
    orderDetail: (id: string) => `/orders/${id}`,
    orderInvoice: (id: string) => `/orders/${id}/invoice`,
    TABLES: '/tables',
    TABLE_NEW: '/tables/new',
    TABLE_COUNTER: '/tables/counter',
    tableEdit: (id: string) => `/tables/${id}/edit`,
    tableQr: (id: string) => `/tables/${id}/qr`,
    SHIPPERS: '/shippers',
    VOUCHERS: '/vouchers',
    POINTS: '/points',
    REFERRALS: '/referrals',
    POSTS: '/posts',
    POST_NEW: '/posts/new',
    postEdit: (id: string) => `/posts/${id}/edit`,
    PAYMENTS: '/payments',
    PAYMENT_CONFIG: '/payment-config',
    PRINTER: '/printer',
    USERS: '/users',
    HRM: '/hrm',
    ATTENDANCE: '/attendance',
    TAXES: '/taxes',
    LOGIN: '/login',
    VOICER: '/voicer',
    FEEDBACK: '/feedback',
    POS_RELEASE: '/pos-release',
    SMS: '/sms',
    SHIPPING: '/shipping',
    GROUP_ORDERS: '/group-orders',
} as const